services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://root_db:5433?u=yugabyte&p=password&d=root_db"
    image: "nocodb/nocodb:latest"
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
  root_db: 
    image: yugabytedb/yugabyte:2024.1.1.0-b137
    command: bash -c 'rm -rf /tmp/.yb.* ; yugabyted start --enable_pg_parity_tech_preview --background=false'
    environment: 
      YSQL_DB: root_db
      YSQL_PASSWORD: password
      YSQL_USER: yugabyte
    healthcheck: 
      interval: 10s
      retries: 10
      test: "postgres/bin/pg_isready -h root_db -U \"$$YSQL_USER\" -d \"$$YSQL_DB\""
      timeout: 2s
    restart: always
    #volumes: 
    #  - "db_data:/root/var"
    ports: 
      - "15433:15433" # YugabyteDB UI console
volumes: 
  db_data: {}
  nc_data: {}
